// Generated by scripts/generate-gallery-manifest.mjs. Do not edit manually.
export const DURABLE_GALLERY_BASE = "https://raw.githubusercontent.com/SUAS-STEM/suas-site/75425f3bafba710b7d8a1b974ac7cab36d44622f/public/images/gallery";
export const GALLERY_PHOTOS = [
    "/images/gallery/20260117_005243476_iOS.jpg",
    "/images/gallery/20260117_005410494_iOS.jpg",
    "/images/gallery/20260117_005729661_iOS.jpg",
    "/images/gallery/20260218_223214240_iOS.png",
    "/images/gallery/20260218_223430630_iOS.png",
    "/images/gallery/20260218_224355150_iOS.png",
    "/images/gallery/20260218_230125050_iOS.png",
    "/images/gallery/IMG-20251124-WA0005.jpg",
    "/images/gallery/IMG-20251124-WA0008.jpg",
    "/images/gallery/IMG-20251124-WA0014.jpg",
    "/images/gallery/IMG-20251124-WA0018.jpg",
    "/images/gallery/IMG-20251124-WA0019.jpg",
    "/images/gallery/IMG-20251124-WA0020.jpg",
    "/images/gallery/IMG-20251124-WA0021.jpg",
    "/images/gallery/IMG-20251124-WA0022.jpg",
    "/images/gallery/IMG-20251124-WA0023.jpg",
    "/images/gallery/IMG-20251124-WA0032.jpg",
    "/images/gallery/IMG-20251124-WA0034.jpg",
    "/images/gallery/IMG-20251124-WA0035.jpg",
    "/images/gallery/IMG-20251124-WA0036.jpg",
    "/images/gallery/IMG-20251124-WA0037.jpg",
    "/images/gallery/IMG-20251124-WA0038.jpg",
    "/images/gallery/IMG-20251124-WA0039.jpg",
    "/images/gallery/IMG-20251124-WA0040.jpg",
    "/images/gallery/IMG-20251124-WA0041.jpg",
    "/images/gallery/WhatsApp%20Image%202026-05-18%20at%2018.15.39%20(1).jpeg",
    "/images/gallery/WhatsApp%20Image%202026-05-18%20at%2018.15.39%20(2).jpeg",
    "/images/gallery/WhatsApp%20Image%202026-05-18%20at%2018.15.39%20(3).jpeg",
    "/images/gallery/WhatsApp%20Image%202026-05-18%20at%2018.15.39%20(4).jpeg",
    "/images/gallery/WhatsApp%20Image%202026-05-18%20at%2018.15.39%20(5).jpeg",
    "/images/gallery/WhatsApp%20Image%202026-05-18%20at%2018.15.39%20(6).jpeg",
    "/images/gallery/WhatsApp%20Image%202026-05-18%20at%2018.15.39.jpeg"
] as const;
export const GALLERY_DISPLAY = [
    "/images/gallery/display/20260117_005243476_iOS.059e355c99d3.webp",
    "/images/gallery/display/20260117_005410494_iOS.fe44f7a086d4.webp",
    "/images/gallery/display/20260117_005729661_iOS.6b884e67dc7e.webp",
    "/images/gallery/display/20260218_223214240_iOS.7ebc3bec8753.webp",
    "/images/gallery/display/20260218_223430630_iOS.509394e8cea5.webp",
    "/images/gallery/display/20260218_224355150_iOS.f12275cb310f.webp",
    "/images/gallery/display/20260218_230125050_iOS.0a65af1b1313.webp",
    "/images/gallery/display/IMG-20251124-WA0005.ece6996409f5.webp",
    "/images/gallery/display/IMG-20251124-WA0008.8dfd07679d0c.webp",
    "/images/gallery/display/IMG-20251124-WA0014.a152388da4a7.webp",
    "/images/gallery/display/IMG-20251124-WA0018.bd7a4f6295f7.webp",
    "/images/gallery/display/IMG-20251124-WA0019.c7d1bd3d62d3.webp",
    "/images/gallery/display/IMG-20251124-WA0020.70269cb45e52.webp",
    "/images/gallery/display/IMG-20251124-WA0021.06991ff21721.webp",
    "/images/gallery/display/IMG-20251124-WA0022.b6b4bd33a3e6.webp",
    "/images/gallery/display/IMG-20251124-WA0023.f05632c7d75c.webp",
    "/images/gallery/display/IMG-20251124-WA0032.5817aeed6477.webp",
    "/images/gallery/display/IMG-20251124-WA0034.c05b9c73723b.webp",
    "/images/gallery/display/IMG-20251124-WA0035.ef6320d1b42f.webp",
    "/images/gallery/display/IMG-20251124-WA0036.b724838d3a34.webp",
    "/images/gallery/display/IMG-20251124-WA0037.1f57bf62f8a1.webp",
    "/images/gallery/display/IMG-20251124-WA0038.9e00e1650e0d.webp",
    "/images/gallery/display/IMG-20251124-WA0039.8ee6c914849d.webp",
    "/images/gallery/display/IMG-20251124-WA0040.7df2ed131852.webp",
    "/images/gallery/display/IMG-20251124-WA0041.41f93d1178de.webp",
    "/images/gallery/display/WhatsApp%20Image%202026-05-18%20at%2018.15.39%20(1).3f760ca977de.webp",
    "/images/gallery/display/WhatsApp%20Image%202026-05-18%20at%2018.15.39%20(2).32125e353f82.webp",
    "/images/gallery/display/WhatsApp%20Image%202026-05-18%20at%2018.15.39%20(3).48efda4f4104.webp",
    "/images/gallery/display/WhatsApp%20Image%202026-05-18%20at%2018.15.39%20(4).3d02ea661323.webp",
    "/images/gallery/display/WhatsApp%20Image%202026-05-18%20at%2018.15.39%20(5).5df2ab004109.webp",
    "/images/gallery/display/WhatsApp%20Image%202026-05-18%20at%2018.15.39%20(6).6ce44dce9faf.webp",
    "/images/gallery/display/WhatsApp%20Image%202026-05-18%20at%2018.15.39.e3c384b37b39.webp"
] as const;
export const GALLERY_THUMBNAILS = [
    "/images/gallery/thumbs/20260117_005243476_iOS.059e355c99d3.webp",
    "/images/gallery/thumbs/20260117_005410494_iOS.fe44f7a086d4.webp",
    "/images/gallery/thumbs/20260117_005729661_iOS.6b884e67dc7e.webp",
    "/images/gallery/thumbs/20260218_223214240_iOS.7ebc3bec8753.webp",
    "/images/gallery/thumbs/20260218_223430630_iOS.509394e8cea5.webp",
    "/images/gallery/thumbs/20260218_224355150_iOS.f12275cb310f.webp",
    "/images/gallery/thumbs/20260218_230125050_iOS.0a65af1b1313.webp",
    "/images/gallery/thumbs/IMG-20251124-WA0005.ece6996409f5.webp",
    "/images/gallery/thumbs/IMG-20251124-WA0008.8dfd07679d0c.webp",
    "/images/gallery/thumbs/IMG-20251124-WA0014.a152388da4a7.webp",
    "/images/gallery/thumbs/IMG-20251124-WA0018.bd7a4f6295f7.webp",
    "/images/gallery/thumbs/IMG-20251124-WA0019.c7d1bd3d62d3.webp",
    "/images/gallery/thumbs/IMG-20251124-WA0020.70269cb45e52.webp",
    "/images/gallery/thumbs/IMG-20251124-WA0021.06991ff21721.webp",
    "/images/gallery/thumbs/IMG-20251124-WA0022.b6b4bd33a3e6.webp",
    "/images/gallery/thumbs/IMG-20251124-WA0023.f05632c7d75c.webp",
    "/images/gallery/thumbs/IMG-20251124-WA0032.5817aeed6477.webp",
    "/images/gallery/thumbs/IMG-20251124-WA0034.c05b9c73723b.webp",
    "/images/gallery/thumbs/IMG-20251124-WA0035.ef6320d1b42f.webp",
    "/images/gallery/thumbs/IMG-20251124-WA0036.b724838d3a34.webp",
    "/images/gallery/thumbs/IMG-20251124-WA0037.1f57bf62f8a1.webp",
    "/images/gallery/thumbs/IMG-20251124-WA0038.9e00e1650e0d.webp",
    "/images/gallery/thumbs/IMG-20251124-WA0039.8ee6c914849d.webp",
    "/images/gallery/thumbs/IMG-20251124-WA0040.7df2ed131852.webp",
    "/images/gallery/thumbs/IMG-20251124-WA0041.41f93d1178de.webp",
    "/images/gallery/thumbs/WhatsApp%20Image%202026-05-18%20at%2018.15.39%20(1).3f760ca977de.webp",
    "/images/gallery/thumbs/WhatsApp%20Image%202026-05-18%20at%2018.15.39%20(2).32125e353f82.webp",
    "/images/gallery/thumbs/WhatsApp%20Image%202026-05-18%20at%2018.15.39%20(3).48efda4f4104.webp",
    "/images/gallery/thumbs/WhatsApp%20Image%202026-05-18%20at%2018.15.39%20(4).3d02ea661323.webp",
    "/images/gallery/thumbs/WhatsApp%20Image%202026-05-18%20at%2018.15.39%20(5).5df2ab004109.webp",
    "/images/gallery/thumbs/WhatsApp%20Image%202026-05-18%20at%2018.15.39%20(6).6ce44dce9faf.webp",
    "/images/gallery/thumbs/WhatsApp%20Image%202026-05-18%20at%2018.15.39.e3c384b37b39.webp"
] as const;
export const GALLERY_CAPTIONS = [
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    },
    {
        "caption": "",
        "people": []
    }
] as const;
